#!/bin/bash -eu

# See https://hackernoon.com/cocoapod-as-xcframework-with-dependencies
# and https://github.com/traveloka/ios-rn-prebuilt

# TODO: Pass DerivedData to the xcodebuild commands to make this immutable

FRAMEWORK_NAME=Johannes
WORKSPACE="$FRAMEWORK_NAME.xcworkspace"
SCHEME=$FRAMEWORK_NAME

ARCHIVES_ROOT=archives
IOS_DEVICE_ARCHIVE_PATH="$ARCHIVES_ROOT/ios_devices.xcarchive"
IOS_SIMULATOR_ARCHIVE_PATH="$ARCHIVES_ROOT/ios_simulators.xcarchive"

FINAL_OUTPUT="$FRAMEWORK_NAME.xcframework"

rm -rf "$ARCHIVES_ROOT"
rm -rf "$FINAL_OUTPUT"

# 1. Archive for iOS
xcodebuild archive \
  -workspace "$WORKSPACE" \
  -scheme "$SCHEME" \
  -configuration Release \
  -sdk iphoneos \
  -archivePath "$IOS_DEVICE_ARCHIVE_PATH" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  SKIP_INSTALL=NO \
  | xcbeautify

# 2. Archive for Simulator
xcodebuild archive \
  -workspace "$WORKSPACE" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -sdk iphonesimulator \
  -archivePath "$IOS_SIMULATOR_ARCHIVE_PATH" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  SKIP_INSTALL=NO \
  | xcbeautify

# Create XCFrameworks for every framework in the archives
XCFRAMEWORKS_DIR=xcframeworks

rm -rf $XCFRAMEWORKS_DIR
mkdir -p $XCFRAMEWORKS_DIR

for FRAMEWORK in $(find $IOS_DEVICE_ARCHIVE_PATH/Products/Library/Frameworks -type d -name "*.framework");
do
  CURRENT_FRAMEWORK_NAME=$(basename "$FRAMEWORK" .framework)

  # TODO: Add support for excluding frameworks?

  # 1. Create XCFrameworks for every framework that was generated by the main
  # framework build process
  FRAMEWORK_RELATIVE_PATH="Products/Library/Frameworks/$CURRENT_FRAMEWORK_NAME.framework"

  xcodebuild \
    -create-xcframework \
    -framework "$IOS_DEVICE_ARCHIVE_PATH/$FRAMEWORK_RELATIVE_PATH" \
    -framework "$IOS_SIMULATOR_ARCHIVE_PATH/$FRAMEWORK_RELATIVE_PATH" \
    -output "$XCFRAMEWORKS_DIR/$CURRENT_FRAMEWORK_NAME.xcframework" \
    | xcbeautify

  # TODO: Do we need this?
  #
  # 2. Exctract any bundle that was generated by the main framework build
  # process
  #
  # Example for reference:
  # BUILT_PRODUCTS_DIR\=/Users/gio/Developer/oss/ios-rn-prebuilt/DerivedData/ios-rn-prebuilt/Build/Intermediates.noindex/ArchiveIntermediates/ios-rn-prebuilt/BuildProductsPath/Release-iphoneos/FBReactNativeSpec
  #
#   for resources in $(find "$BUILT_PRODUCTS_DIR/../.." -type d -name "*.bundle");
#   do
#     cp -R $resources $SRCROOT/Frameworks/
#   done
done
