#!/bin/bash -eu

RESTORE_ONLY='false'
while [[ "$#" -gt 0 ]]; do
	case $1 in
		--restore-only) RESTORE_ONLY='true' ;;
		*) break ;;
	esac
	shift
done

PLATFORM=$(uname -s)
ARCHITECTURE=$(uname -m)
NODE_VERSION=$(node --version)
PACKAGE_VERSION=$(jq -r .version package.json)

PACKAGE_HASH=$(hash_file package-lock.json)
GUTENBERG_PACKAGE_HASH=$(hash_file gutenberg/package-lock.json)
JETPACK_PACKAGE_HASH=$(hash_file jetpack/pnpm-lock.yaml)
BLOCK_EXPERIMENTS_PACKAGE_HASH=$(hash_file block-experiments/yarn.lock)

NPM_CACHEKEY="$BUILDKITE_PIPELINE_SLUG-npm-$PLATFORM-$ARCHITECTURE-node-$NODE_VERSION-$PACKAGE_HASH-$GUTENBERG_PACKAGE_HASH"
NPM_CACHE_FOLDER=".npm"

PNPM_CACHEKEY="$BUILDKITE_PIPELINE_SLUG-pnpm-$PLATFORM-$ARCHITECTURE-node-$NODE_VERSION-$JETPACK_PACKAGE_HASH"
PNPM_CACHE_FOLDER="store"

YARN_CACHEKEY="$BUILDKITE_PIPELINE_SLUG-yarn-$PLATFORM-$ARCHITECTURE-node-$NODE_VERSION-$BLOCK_EXPERIMENTS_PACKAGE_HASH"
YARN_CACHE_FOLDER="Yarn"

I18N_CACHEKEY="$BUILDKITE_PIPELINE_SLUG-i18n-$PLATFORM-$ARCHITECTURE-node-$NODE_VERSION-$PACKAGE_VERSION"
I18N_CACHE_FOLDER="src/i18n-cache"

if [ "$PLATFORM" = "Darwin" ]; then
  PNPM_PATH="$HOME/Library/pnpm"
elif [ "$PLATFORM" = "Linux" ]; then
  PNPM_PATH="$HOME/.local/share/pnpm"
fi

npx yarn cache dir

echo "--- :npm: Restore cache if present"
pushd "$HOME"
restore_cache "$NPM_CACHEKEY"
popd

mkdir -p "$PNPM_PATH"
pushd "$PNPM_PATH"
restore_cache "$PNPM_CACHEKEY"
popd

restore_cache "$I18N_CACHEKEY"

if [[ "${RESTORE_ONLY}" ==  'true' ]]; then
  echo 'Exiting after restoring caches as per --restore-only call parameter.'
  exit 0
fi

echo "--- :npm: Install Node dependencies"

npm ci --unsafe-perm --prefer-offline --no-audit --no-progress "$@"

echo "--- :npm: Save cache if necessary"
# Notice that we don't cache the local node_modules.
# Those get regenerated by npm ci as per Node reccomendations.
# What we are caching is the root npm folder, which stores pacakge downloads so they are available if the package.json resolution demands them.
#
# npm stores temporary files in ~/.npm that we don't want to extract because they might run into naming conflicts.
# So, before archiving it, we remove those tmp files.
#
# Example: https://buildkite.com/automattic/gutenberg-mobile/builds/8857#018e37eb-7afc-4280-b736-cba76f02f1a3/524
rm -rf "$HOME/.npm/_cacache/tmp"
pushd "$HOME"
save_cache "$NPM_CACHE_FOLDER" "$NPM_CACHEKEY"
popd

if [ -d "$I18N_CACHE_FOLDER" ]; then
  save_cache "$I18N_CACHE_FOLDER" "$I18N_CACHEKEY"
else
  echo "Directory $I18N_CACHE_FOLDER does not exist. Skipping..."
fi

# If we attempted to save the pnpm cache when npm run with '--prefix gutenberg', the command might fail.
# That's because the Jetpack submodule alone uses pnpm.
# Therefore, if no pnpm cache was available at the start, running with '--prefix gutenberg' would not have generated one and 'save_cache' would fail to find it.
if echo "$@" | grep -q -- '--prefix gutenberg'; then
  echo 'Skipping pnpm cach save due to --prefix gutenberg parameter while PNPM is used in Jetpack.'
  exit 0
fi

pushd "$PNPM_PATH"
save_cache "$PNPM_CACHE_FOLDER" "$PNPM_CACHEKEY"
popd
