x-common-params:
  - &git-shallow-clone-plugin
    automattic/git-shallow-clone#trunk
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/gb-mobile-image:latest"
      environment:
        - "CI=true"
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - "WP_CLI_ALLOW_ROOT=true"
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/android-build-image:v1.3.0"
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - "AWS_ACCESS_KEY"
        - "AWS_SECRET_KEY"

steps:
  - block: "Request trigger Android bundle and builds"
    branches: "dependabot/submodules/*"

  - label: Lint and Unit Tests
    key: unit-tests
    plugins:
      - *gb-mobile-docker-container
    command: |
      source /root/.bashrc

      echo "+++ 🔎 "
      set -x
      npm config get
      set +x

      echo "+++ 🔎 "
      set -x
      whoami
      set +x

      echo "+++ 🔎 "
      set -x
      npm config get cache
      set +x

      echo "--- :npm"
      npm ci --unsafe-perm --prefer-offline --no-audit --no-progress --logLevel=verbose
