x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/gb-mobile-image:latest"
      environment:
        - "CI=true"
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - "WP_CLI_ALLOW_ROOT=true"
  - &git-cache-plugin
    automattic/git-s3-cache#1.1.4:
      # Ensure these settings match what's defined in cache-builder.yml
      bucket: a8c-repo-mirrors
      repo: automattic/gutenberg-mobile/
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/android-build-image:v1.3.0"
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - "AWS_ACCESS_KEY"
        - "AWS_SECRET_KEY"

steps:
  - label: iOS Build
    command: |
      # This build failed because the git-s3-cache plugin didn't checkout the repo due to finding the env var set
      # https://buildkite.com/automattic/gutenberg-mobile/builds/7033#018a447e-aca5-4b07-ba2d-3ea961873d8d
      echo '+++ :bug: Check IS_VM_HOST value'
      echo $IS_VM_HOST
      echo $$IS_VM_HOST

      echo '--- :npm: Setup Node dependencies'
      npm ci

      echo '--- :react: Build iOS app for E2E testing'
      npm run core test:e2e:build-app:ios

      echo '--- :react: Build iOS bundle for E2E testing'
      npm run test:e2e:bundle:ios

      echo '--- :zip: Prepare artifact for SauceLab upload'
      WORK_DIR=$$(pwd) \
        && pushd ./gutenberg/packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator \
        && zip -r $$WORK_DIR/gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip GutenbergDemo.app \
        && popd
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
      - automattic/nvm#0.1.0
      - *git-cache-plugin
    artifact_paths:
      - ./gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-14.3.1
      TEST_RN_PLATFORM: ios
      TEST_ENV: sauce
