x-common-params:
  - &git-shallow-clone-plugin
    automattic/git-shallow-clone#trunk
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/android-build-image:v1.3.0"
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - "AWS_ACCESS_KEY"
        - "AWS_SECRET_KEY"

steps:
  - block: "Request trigger Android bundle and builds"
    branches: "dependabot/submodules/*"

  - label: "Build JS Bundles"
    key: "js-bundles"
    plugins:
      - *git-shallow-clone-plugin
      - docker#v3.8.0:
          image: "public.ecr.aws/automattic/gb-mobile-image:latest"
          environment:
            - "CI=true"
            # Allow WP-CLI to be run as root, otherwise it throws an exception.
            # Reference: https://git.io/J9q2S
            - "WP_CLI_ALLOW_ROOT=true"
    command: |
        source /root/.bashrc

        echo "--- :node: Setup Node environment"
        nvm install && nvm use

        echo "--- :npm: Install Node dependencies"
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        if [[ -z "$BUILDKITE_TAG" ]]; then
          echo "--- :package: Skip bundle prep work"
        else
          echo "--- :package: Run bundle prep work"
          npm run prebundle:js
        fi

        echo "--- :android: Build Android bundle"
        npm run bundle:android
        node gutenberg/node_modules/react-native/scripts/compose-source-maps.js bundle/android/App.text.js.map bundle/android/App.js.map -o bundle/android/App.composed.js.map

        echo "--- :arrow_up: Upload Android bundle artifact"
        buildkite-agent artifact upload bundle/android/App.js
        buildkite-agent artifact upload bundle/android/App.composed.js.map

        echo "--- :ios: Build iOS bundle"
        npm run bundle:ios
        node gutenberg/node_modules/react-native/scripts/compose-source-maps.js bundle/ios/App.text.js.map bundle/ios/App.js.map -o bundle/ios/App.composed.js.map

        echo "--- :arrow_up: Upload iOS bundle artifact"
        buildkite-agent artifact upload bundle/ios/App.js
        buildkite-agent artifact upload bundle/ios/App.composed.js.map
  - label: "Build Android RN Aztec & Publish to S3"
    key: "publish-react-native-aztec-android"
    plugins:
      - *git-shallow-clone-plugin
      - *publish-android-artifacts-docker-container
    command: |
        .buildkite/publish-react-native-aztec-android-artifacts.sh

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on:
      - "js-bundles"
      - "publish-react-native-aztec-android"
    plugins:
      - *git-shallow-clone-plugin
      - *publish-android-artifacts-docker-container
    command: |
        .buildkite/publish-react-native-bridge-android-artifacts.sh

  - label: Build iOS RN XCFramework & Publish to S3
    depends_on: js-bundles
    command: .buildkite/publish-react-native-ios-artifacts.sh
    artifact_paths:
      - ios-xcframework/build/xcframeworks/*.tar.gz
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
      - *git-shallow-clone-plugin
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-14.3.1
