x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/gb-mobile-image:latest'
      environment:
        - 'CI=true'
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - 'WP_CLI_ALLOW_ROOT=true'
  - &git-cache-plugin
    automattic/git-s3-cache#1.1.4:
      # Ensure these settings match what's defined in cache-builder.yml
      bucket: a8c-repo-mirrors
      repo: automattic/gutenberg-mobile/
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/android-build-image:v1.3.0'
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - 'AWS_ACCESS_KEY'
        - 'AWS_SECRET_KEY'
  - &xcode_agent_env
    IMAGE_ID: xcode-14.3.1

steps:
  - label: ':saucelabs: iOS Build and SauceLabs'
    key: ios-build-and-saucelabs
    command: .buildkite/build-ios.sh
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
      - *git-cache-plugin
    artifact_paths:
      - ./gutenberg/packages/react-native-editor/ios/GutenbergDemo.app.zip
    agents:
      queue: mac
    env: *xcode_agent_env

  # TODO: Notify failures via Slack!

  # Verified this works
  # https://buildkite.com/automattic/gutenberg-mobile/builds/7083#_
  - label: Test iOS on Device – Canary Pages
    depends_on: ios-build-and-saucelabs
    command: .buildkite/test-ios.sh --canary
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
      - *git-cache-plugin
    artifact_paths:
      - reports/test-results/ios-test-results.xml
    agents:
      queue: mac
    env: *xcode_agent_env

  # TODO: Make conditional based on branch, as per CircleCI configs
  - block: "Full UI Tests"
    prompt: "Run full UI tests suites?"

  - label: Test iOS on Device – Full iPhone
    depends_on: ios-build-and-saucelabs
    command: .buildkite/test-ios.sh
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
      - *git-cache-plugin
    artifact_paths:
      - reports/test-results/ios-test-results.xml
    agents:
      queue: mac
    env: *xcode_agent_env

  - label: Test iOS on Device – Full iPad
    depends_on: ios-build-and-saucelabs
    command: .buildkite/test-ios.sh --ipad
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
      - *git-cache-plugin
    artifact_paths:
      - reports/test-results/ios-test-results.xml
    agents:
      queue: mac
    env: *xcode_agent_env
