x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/gb-mobile-image:latest"
      environment:
        - "CI=true"
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - "WP_CLI_ALLOW_ROOT=true"
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - "AWS_ACCESS_KEY"
        - "AWS_SECRET_KEY"

steps:
  - block: "Request trigger Android bundle and builds"
    branches: "dependabot/submodules/*"

  # - label: Build npm cache
  #   key: build-npm
  #   plugins:
  #     - *gb-mobile-docker-container
  #     - automattic/git-shallow-clone
  #   command: |
  #     source /root/.bashrc

  #     echo "--- :node: Setup Node environment"
  #     nvm install && nvm use

  #     # Note that `npm ci` deletes node_modules and installs from scratch, for a deterministic CI build.
  #     # For that reason, we don't attempt to download them
  #     echo "--- :npm: Build dependencies cache (gutenberg-mobile)"
  #     npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

  #     echo "--- :bug: Check npm artifacts"
  #     set -x
  #     ls -a /root
  #     ls -a /root/.npm
  #     ls node_modules
  #     ls src/i18n-cache
  #     # On a macOS machine, this would be ~/Library/pnpm/store/v3
  #     ls /root/.local/share/pnpm/store/v3
  #     set +x

  #     echo "--- :arrow_up: Upload node_modules"
  #     tar --create --gzip --file=node_modules.tar.gz --directory=. node_modules
  #     buildkite-agent artifact upload node_modules.tar.gz

  #     echo "--- :arrow_up: Upload i18n-cache"
  #     tar --create --gzip --file=i18n_cache.tar.gz --directory=. src/i18n-cache
  #     buildkite-agent artifact upload i18n_cache.tar.gz

  #     echo "--- :arrow_up: Upload .npm cache"
  #     tar --create --gzip --file=npm_cache.tar.gz --directory=/root .npm
  #     buildkite-agent artifact upload npm_cache.tar.gz

  #     echo "--- :arrow_up: Upload pnpm store"
  #     tar --create --gzip --file=pnpm_cache.tar.gz --directory=/root .local/share/pnpm/store/v3
  #     buildkite-agent artifact upload pnpm_cache.tar.gz

  - label: Lint and Unit Tests
    # depends_on: build-npm
    key: unit-tests
    plugins:
      - *gb-mobile-docker-container
      - automattic/git-shallow-clone
    command: |
      source /root/.bashrc

      echo "--- :node: Setup Node environment"
      nvm install && nvm use

      echo "--- :arrow_down: Download .npm cache"
      buildkite-agent artifact download npm_cache.tar.gz . --build 01886ef6-fdc4-465a-92e5-d4e3721bc459
      tar --extract --gzip --file=npm_cache.tar.gz --directory=/root

      echo "--- :arrow_down: Download src/i18n-cache"
      buildkite-agent artifact download i18n_cache.tar.gz . --build 01886ef6-fdc4-465a-92e5-d4e3721bc459
      tar --extract --gzip --file=i18n_cache.tar.gz --directory=.

      echo "--- :arrow_down: Download pnpm store"
      buildkite-agent artifact download pnpm_cache.tar.gz . --build 01886ef6-fdc4-465a-92e5-d4e3721bc459
      tar --extract --gzip --file=pnpm_cache.tar.gz --directory=/root

      echo "--- :bug: Check npm artifacts"
      set -x
      ls -a /root
      ls -a /root/.npm
      ls src/i18n-cache
      # On a macOS machine, this would be ~/Library/pnpm/store/v3
      ls /root/.local/share/pnpm/store/v3
      set +x

      # echo "--- :npm: Download node_modules"
      # buildkite-agent artifact download node_modules.tar.gz .
      # tar --extract --gzip --file=node_modules.tar.gz

      echo "--- :npm: Fast dependencies install (gutenbreg-mobile)"
      npm install --prefer-offline --no-audit --no-progress --ignore-scripts

      echo "--- :npm: Fast dependencies install (gutenberg)"
      npm install --prefix gutenberg --prefer-offline --no-audit

      echo "--- :bug: Info ./node_modules/rimraf"
      ls ./node_modules/rimraf

      echo "--- :node: Lint and Unit Tests"
      ./bin/ci-checks-js.sh
    artifact_paths:
      - ./*-tests-out.log

  - label: "Build JS Bundles"
    depends_on: "unit-tests"
    key: "js-bundles"
    plugins:
      - *gb-mobile-docker-container
    command: |
        source /root/.bashrc

        echo "--- :node: Setup Node environment"
        nvm install && nvm use

        echo "--- :npm: Download cached dependencies"
        buildkite-agent artifact download node_modules.tar.gz .
        tar --extract --gzip --file=node_modules.tar.gz

        echo "--- :package: Run bundle prep work"
        npm run prebundle:js

        echo "--- :android: Build Android bundle"
        npm run bundle:android

        echo "--- :arrow_up: Upload Android bundle artifact"
        buildkite-agent artifact upload bundle/android/App.js

        echo "--- :ios: Build iOS bundle"
        npm run bundle:ios

        echo "--- :arrow_up: Upload iOS bundle artifact"
        buildkite-agent artifact upload bundle/ios/App.js
  - label: "Build Android RN Aztec & Publish to S3"
    depends_on: unit-tests
    key: "publish-react-native-aztec-android"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
        .buildkite/publish-react-native-aztec-android-artifacts.sh

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on:
      - "js-bundles"
      - "publish-react-native-aztec-android"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
        .buildkite/publish-react-native-bridge-android-artifacts.sh

  - label: Build iOS RN XCFramework & Publish to S3
    depends_on: js-bundles
    command: .buildkite/publish-react-native-ios-artifacts.sh
    artifact_paths:
      - ios-xcframework/build/xcframeworks/*.tar.gz
    plugins:
      - automattic/a8c-ci-toolkit#2.17.0
      - automattic/git-shallow-clone
     gents:
      queue: mac
    env:
      IMAGE_ID: xcode-14.3
