x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/gb-mobile-image:latest'
      environment:
        - 'CI=true'
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - 'WP_CLI_ALLOW_ROOT=true'
        # Increase max available memory for node
        - 'NODE_OPTIONS="--max-old-space-size=4096"'
  - &git-cache-plugin
    automattic/git-s3-cache#1.1.4:
      # Ensure these settings match what's defined in cache-builder.yml
      bucket: a8c-repo-mirrors
      repo: automattic/gutenberg-mobile/
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/android-build-image:v1.3.0'
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - 'AWS_ACCESS_KEY'
        - 'AWS_SECRET_KEY'
  - &nvm_plugin
    automattic/nvm#0.3.0:
      # This is an attempt to fix curl error (92) during installing nodejs.
      curlrc: --http1.1
  - &ci_toolkit_plugin
    automattic/a8c-ci-toolkit#2.18.2
  - &xcode_agent_env
    IMAGE_ID: xcode-15.0.1
  - &is_branch_for_full_ui_tests
    build.branch == 'trunk' || build.branch =~ /^release.*/ || build.branch =~ /^dependabot\/submodules.*/
  - &is_branch_for_quick_ui_tests
    build.branch != 'trunk' && build.branch !~ /^release.*/ && build.branch !~ /^dependabot\/submodules.*/

steps:
  - label: Check Ruby on gb-mobile Docker
    plugins:
      - *gb-mobile-docker-container
      - *git-cache-plugin
    command: echo '--- Check Ruby' && which ruby

  - label: Check Ruby on Android queue
    plugins:
      - *git-cache-plugin
      - *nvm_plugin
    command: echo '--- Check Ruby' && which ruby
    agents:
      queue: android

  - label: Check Ruby on publish-android-artifacts Docker
    plugins:
      - *git-cache-plugin
      - *publish-android-artifacts-docker-container
    command: echo '--- Check Ruby' && which ruby

  - label: Check Ruby on macOS (expected to pass)
    command: echo '--- Check Ruby' && which ruby
    plugins:
      - *ci_toolkit_plugin
      - *nvm_plugin
      - *git-cache-plugin
    agents:
      queue: mac
    env: *xcode_agent_env
