x-common-params:
  &publish-android-artifacts-docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
    propagate-environment: true
    environment:
      # DO NOT MANUALLY SET THESE VALUES!
      # They are passed from the Buildkite agent to the Docker container
      - "AWS_ACCESS_KEY"
      - "AWS_SECRET_KEY"

steps:
  #
  # Disabled for faster feedback
  #

  # - block: "Request trigger Android bundle and builds"
  #   branches: "dependabot/submodules/*"

  # - label: "Bundle Android"
  #   key: "bundle-android"
  #   plugins:
  #     - docker#v3.8.0:
  #         image: "public.ecr.aws/automattic/gb-mobile-image:latest"
  #         environment:
  #           - "CI=true"
  #           # Allow WP-CLI to be run as root, otherwise it throws an exception.
  #           # Reference: https://git.io/J9q2S
  #           - "WP_CLI_ALLOW_ROOT=true"
  #   command: |
  #       source /root/.bashrc

  #       nvm install && nvm use
  #       npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

  #       npm run prebundle:js
  #       npm run bundle:android

  #       buildkite-agent artifact upload bundle/android/App.js

  # - label: "Build Android RN Aztec & Publish to S3"
  #   key: "publish-react-native-aztec-android"
  #   plugins:
  #     - *publish-android-artifacts-docker-container
  #   command: |
  #       .buildkite/publish-react-native-aztec-android-artifacts.sh

  # - label: "Build Android RN Bridge & Publish to S3"
  #   depends_on:
  #     - "bundle-android"
  #     - "publish-react-native-aztec-android"
  #   plugins:
  #     - *publish-android-artifacts-docker-container
  #   command: |
  #       .buildkite/publish-react-native-bridge-android-artifacts.sh

  # - label: Build iOS RN XCFramework
  #   command: cd ./ios-xcframework && ./build.sh
  #   plugins:
  #     - peakon/git-shallow-clone#v0.0.1:
  #         depth: 1
  #   agents:
  #     queue: mac
  #   env:
  #     IMAGE_ID: xcode-14.2

  - label: ':npm: Validate dependencies'
    key: validate-dependencies
    plugins:
      - automattic/a8c-ci-toolkit#2.15.1
      - peakon/git-shallow-clone#v0.0.1:
          depth: 1
      - docker#v3.9.0:
          image: node:14 # TODO read value from `.nvmrc`
    command: |
      echo "--- :node: Node info"
      echo "Node version: $(node --version)"
      echo "--- :npm: npm ci"
      npm ci --prefer-offline --no-audit

  - group: ':android: Android Tests'
    steps:
      - label: 'Android Build'
        key: 'android-build'
        depends_on: 'validate-dependencies'
        command: echo "test"

      - label: 'Android JS Tests'
        key: 'android-js-tests'
        depends_on: 'android-build'
        command: echo "test"

  - group: ':ios: iOS Tests'
    steps:
      - label: 'iOS Build'
        key: 'ios-build'
        depends_on: 'validate-dependencies'
        command: echo "test"

      - label: 'iOS JS Tests'
        key: 'ios-js-tests'
        depends_on: 'ios-build'
        command: echo "test"
