x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/gb-mobile-image:latest'
      environment:
        - 'CI=true'
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - 'WP_CLI_ALLOW_ROOT=true'
  - &git-cache-plugin
    automattic/git-s3-cache#1.1.4:
      # Ensure these settings match what's defined in cache-builder.yml
      bucket: a8c-repo-mirrors
      repo: automattic/gutenberg-mobile/
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/android-build-image:v1.3.0'
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - 'AWS_ACCESS_KEY'
        - 'AWS_SECRET_KEY'
        - 'SAUCE_USERNAME'
        - 'SAUCE_ACCESS_KEY'
  - &xcode_agent_env
    IMAGE_ID: xcode-14.3.1
  - &is_branch_for_full_ui_tests
    build.branch == 'trunk' || build.branch =~ /^release.*/ || build.branch =~ /^dependabot\/submodules.*/
  - &is_branch_for_quick_ui_tests
    build.branch != 'trunk' && build.branch !~ /^release.*/ && build.branch !~ /^dependabot\/submodules.*/

steps:
  - label: Android packages unit tests
    key: android-packages-unit-tests
    plugins:
      - *publish-android-artifacts-docker-container
      - *git-cache-plugin
    command: .buildkite/commands/test-unit-android.sh
    artifact_paths:
      - gutenberg/packages/react-native-bridge/build/test-results/test*/*.xml
    notify:
      - github_commit_status:
          context: Test Android packages

  - label: Android Build and Sauce Labs
    key: android-build-and-saucelabs
    plugins:
      - *publish-android-artifacts-docker-container
      - *git-cache-plugin
    command: .buildkite/commands/build-android.sh

  - label: Test Android on Device – Canary Pages
    depends_on: android-build-and-saucelabs
    plugins:
      - *publish-android-artifacts-docker-container
      - *git-cache-plugin
    command: .buildkite/commands/test-e2e-android.sh --canary
    artifact_paths:
      - reports/test-results/android-test-results.xml
    notify:
      - github_commit_status:
          context: Test Android on Device - Canaries
