x-common-params:
  &publish-android-artifacts-docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
    propagate-environment: true
    environment:
      # DO NOT MANUALLY SET THESE VALUES!
      # They are passed from the Buildkite agent to the Docker container
      - "AWS_ACCESS_KEY"
      - "AWS_SECRET_KEY"

steps:
  - label: Build iOS RN XCFramework & Publish to S3
    command: .buildkite/publish-react-native-ios-artifacts.sh
    plugins:
      - automattic/a8c-ci-toolkit#2.16.0
      - peakon/git-shallow-clone#v0.0.1:
          depth: 1
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-14.3.1
