x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/gb-mobile-image:latest"
      environment:
        - "CI=true"
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - "WP_CLI_ALLOW_ROOT=true"
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - "AWS_ACCESS_KEY"
        - "AWS_SECRET_KEY"

steps:
  - block: "Request trigger Android bundle and builds"
    branches: "dependabot/submodules/*"

  - label: Build npm cache
    key: build-npm
    plugins:
      - *gb-mobile-docker-container
      - automattic/git-shallow-clone
    command: |
      source /root/.bashrc

      echo "--- :node: Setup Node environment"
      nvm install && nvm use

      echo "--- :bug: Info"
      set -x
      ls /root
      ls -a /root
      set +x

      # Note that `npm ci` deletes node_modules and installs from scratch, for a deterministic CI build
      echo "--- :npm: Build dependencies cache"
      npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

      echo "--- :bug: Info"
      set -x
      ls /root
      ls -a /root
      set +x

      echo "--- :npm: Upload node_modules"
      tar --create --gzip --file=node_modules.tar.gz --directory=. node_modules
      buildkite-agent artifact upload node_modules.tar.gz

      echo "--- :arrow_up: Upload vendor/.npm cache"
      tar --create --gzip --file=npm_cache.tar.gz --directory=./vendor .npm
      buildkite-agent artifact upload npm_cache.tar.gz
