x-common-params:
  - &gb-mobile-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/gb-mobile-image:latest'
      environment:
        - 'CI=true'
        # Allow WP-CLI to be run as root, otherwise it throws an exception.
        # Reference: https://git.io/J9q2S
        - 'WP_CLI_ALLOW_ROOT=true'
  - &git-cache-plugin
    automattic/git-s3-cache#1.1.4:
      # Ensure these settings match what's defined in cache-builder.yml
      bucket: a8c-repo-mirrors
      repo: automattic/gutenberg-mobile/
  - &publish-android-artifacts-docker-container
    docker#v3.8.0:
      image: 'public.ecr.aws/automattic/android-build-image:v1.3.0'
      propagate-environment: true
      environment:
        # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - 'AWS_ACCESS_KEY'
        - 'AWS_SECRET_KEY'
  - &nvm_plugin
    automattic/nvm#0.3.0:
      # This is an attempt to fix curl error (92) during installing nodejs.
      curlrc: --http1.1
  - &ci_toolkit_plugin
    automattic/a8c-ci-toolkit#2.18.2
  - &xcode_agent_env
    IMAGE_ID: xcode-14.3.1
  - &is_branch_for_full_ui_tests
    build.branch == 'trunk' || build.branch =~ /^release.*/ || build.branch =~ /^dependabot\/submodules.*/
  - &is_branch_for_quick_ui_tests
    build.branch != 'trunk' && build.branch !~ /^release.*/ && build.branch !~ /^dependabot\/submodules.*/

steps:
  - label: Android Build for Sauce Labs
    key: android-build-and-saucelabs
    command: |
      # Tried the Docker route, but this container lacks the Java setup,
      # and the other Node...
      #
      # For example, see this build:
      # https://buildkite.com/automattic/gutenberg-mobile/builds/7702#018b6b82-f52e-426d-9944-f60f4a2b14dd
      # echo "--- :docker: Additional Docker image setup"
      # source /root/.bashrc

      # echo "--- :docker::node: Setup Node environment"
      # nvm install && nvm use

      .buildkite/commands/build-android.sh
    plugins:
      # See comment about Docker above
      # - *gb-mobile-docker-container
      - *ci_toolkit_plugin
      - *nvm_plugin
      - *git-cache-plugin
    artifact_paths:
      - ./gutenberg/packages/react-native-editor/android/app/build/outputs/apk/debug/app-debug.apk
    agents:
      queue: android-staging

  - label: Test Android on Device – Canary Pages (Docker)
    depends_on: android-build-and-saucelabs
    command: |
      echo "--- :docker: Additional Docker image setup"
      source /root/.bashrc

      echo "--- :docker::node: Setup Node environment"
      nvm install && nvm use

      .buildkite/commands/test-android.sh --canary
    plugins:
      - *gb-mobile-docker-container
      - *git-cache-plugin
    artifact_paths:
      - reports/test-results/android-test-results.xml
    env:
      JEST_JUNIT_OUTPUT_FILE: reports/test-results/android-test-results.xml
    # notify:
    #   - github_commit_status:
    #       context: Test Android on Device - Canaries

  - label: Test Android on Device – Canary Pages (Linux)
    depends_on: android-build-and-saucelabs
    command: .buildkite/commands/test-android.sh --canary
    plugins:
      - *ci_toolkit_plugin
      - *nvm_plugin
      - *git-cache-plugin
    artifact_paths:
      - reports/test-results/android-test-results.xml
    env:
      JEST_JUNIT_OUTPUT_FILE: reports/test-results/android-test-results.xml
    # notify:
    #   - github_commit_status:
    #       context: Test Android on Device - Canaries

  - label: Test Android on Device – Canary Pages (macOS)
    depends_on: android-build-and-saucelabs
    command: .buildkite/commands/test-android.sh --canary
    plugins:
      - *ci_toolkit_plugin
      - *nvm_plugin
      - *git-cache-plugin
    artifact_paths:
      - reports/test-results/android-test-results.xml
    agents:
      queue: mac
    env:
      <<: *xcode_agent_env
      JEST_JUNIT_OUTPUT_FILE: reports/test-results/android-test-results.xml
    # notify:
    #   - github_commit_status:
    #       context: Test Android on Device - Canaries
