# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cocoapods', '~> 1.12'
# Let the release-toolkit drive which Fastlane version to use.
# See also https://github.com/wordpress-mobile/release-toolkit/issues/482
gem 'fastlane'
gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', branch: 'mokagio/add-if_exists-to-s3-upload'
