
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/FBReactNativeSpec/EventEmitters.h>
#include <react/renderer/components/FBReactNativeSpec/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>

namespace facebook {
namespace react {

extern const char ActivityIndicatorViewComponentName[];

/*
 * `ShadowNode` for <ActivityIndicatorView> component.
 */
using ActivityIndicatorViewShadowNode = ConcreteViewShadowNode<
    ActivityIndicatorViewComponentName,
    ActivityIndicatorViewProps>;

extern const char DatePickerComponentName[];

/*
 * `ShadowNode` for <DatePicker> component.
 */
using DatePickerShadowNode = ConcreteViewShadowNode<
    DatePickerComponentName,
    DatePickerProps,
DatePickerEventEmitter>;

extern const char AndroidDrawerLayoutComponentName[];

/*
 * `ShadowNode` for <AndroidDrawerLayout> component.
 */
using AndroidDrawerLayoutShadowNode = ConcreteViewShadowNode<
    AndroidDrawerLayoutComponentName,
    AndroidDrawerLayoutProps,
AndroidDrawerLayoutEventEmitter>;

extern const char RCTMaskedViewComponentName[];

/*
 * `ShadowNode` for <RCTMaskedView> component.
 */
using RCTMaskedViewShadowNode = ConcreteViewShadowNode<
    RCTMaskedViewComponentName,
    RCTMaskedViewProps>;

extern const char RCTProgressViewComponentName[];

/*
 * `ShadowNode` for <RCTProgressView> component.
 */
using RCTProgressViewShadowNode = ConcreteViewShadowNode<
    RCTProgressViewComponentName,
    RCTProgressViewProps>;

extern const char AndroidSwipeRefreshLayoutComponentName[];

/*
 * `ShadowNode` for <AndroidSwipeRefreshLayout> component.
 */
using AndroidSwipeRefreshLayoutShadowNode = ConcreteViewShadowNode<
    AndroidSwipeRefreshLayoutComponentName,
    AndroidSwipeRefreshLayoutProps,
AndroidSwipeRefreshLayoutEventEmitter>;

extern const char PullToRefreshViewComponentName[];

/*
 * `ShadowNode` for <PullToRefreshView> component.
 */
using PullToRefreshViewShadowNode = ConcreteViewShadowNode<
    PullToRefreshViewComponentName,
    PullToRefreshViewProps,
PullToRefreshViewEventEmitter>;

extern const char AndroidHorizontalScrollContentViewComponentName[];

/*
 * `ShadowNode` for <AndroidHorizontalScrollContentView> component.
 */
using AndroidHorizontalScrollContentViewShadowNode = ConcreteViewShadowNode<
    AndroidHorizontalScrollContentViewComponentName,
    AndroidHorizontalScrollContentViewProps>;

extern const char SwitchComponentName[];

/*
 * `ShadowNode` for <Switch> component.
 */
using SwitchShadowNode = ConcreteViewShadowNode<
    SwitchComponentName,
    SwitchProps,
SwitchEventEmitter>;

extern const char UnimplementedNativeViewComponentName[];

/*
 * `ShadowNode` for <UnimplementedNativeView> component.
 */
using UnimplementedNativeViewShadowNode = ConcreteViewShadowNode<
    UnimplementedNativeViewComponentName,
    UnimplementedNativeViewProps>;

} // namespace react
} // namespace facebook
