name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      gbm-cli:
        description: 'gbm-cli version'
        default: 'latest'

jobs:
  prepare_release:
    runs-on: macos-latest
    name: Prepare Gutenberg Mobile release
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GITHUB_USER: ${{ github.actor }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21

      - name: Install CLI
        run: go install github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/gbm-cli@${{ github.event.inputs.gbm-cli }}

      - name: Create PR
        run: yes | gbm-cli release prepare gbm ${{ github.event.inputs.version }}

